controller_list:
  - name: fake_arm_group_controller
    type: $(arg fake_execution_type)
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
  - name: fake_gripper_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - force_gripper_controller
initial:  # Define initial robot poses per group
  - group: arm_group
    pose: arm_init_pose
  - group: gripper_arm
    pose: open_gripper